from typing import Any, Protocol


class LoggerPort(Protocol):
    """Port for structured logging. Compatible with structlog.BoundLogger without importing it."""

    def debug(self, msg: str, **kwargs: Any) -> None: ...

    def info(self, msg: str, **kwargs: Any) -> None: ...

    def warning(self, msg: str, **kwargs: Any) -> None: ...

    def error(self, msg: str, **kwargs: Any) -> None: ...

    def bind(self, **kwargs: Any) -> "LoggerPort": ...
