"""luoc do khoi tao

Revision ID: 2cb749301f2c
Revises: 
Create Date: 2026-09-21 12:24:44.888464
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '2cb749301f2c'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_nho_dem',
    sa.Column('khoa', sa.String(length=512), nullable=False),
    sa.Column('gia_tri', sa.Text(), nullable=False),
    sa.Column('het_han', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('khoa')
    )
    op.create_table('dau_vet_goi',
    sa.Column('khoa', sa.String(length=512), nullable=False),
    sa.Column('moc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('khoa', 'moc')
    )
    op.create_table('doan_van',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.String(length=256), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'chunk_id')
    )
    op.create_table('khoa_api',
    sa.Column('bam', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('ten', sa.String(length=256), nullable=False),
    sa.Column('tao_luc', sa.Float(), nullable=False),
    sa.Column('het_han_luc', sa.Float(), nullable=True),
    sa.Column('thu_hoi_luc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('bam')
    )
    op.create_table('ngan_sach_ngay',
    sa.Column('khoa', sa.String(length=512), nullable=False),
    sa.Column('ngay', sa.String(length=16), nullable=False),
    sa.Column('so_lan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('khoa', 'ngay')
    )
    op.create_table('phan_hoi',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'thu_tu')
    )
    op.create_table('tai_lieu',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'doc_id')
    )
    op.create_table('tin_nhan',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'session_id', 'thu_tu')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tin_nhan')
    op.drop_table('tai_lieu')
    op.drop_table('phan_hoi')
    op.drop_table('ngan_sach_ngay')
    op.drop_table('khoa_api')
    op.drop_table('doan_van')
    op.drop_table('dau_vet_goi')
    op.drop_table('bo_nho_dem')
    # ### end Alembic commands ###
