"""them bang hoi_thoai

Revision ID: 80e25247c90a
Revises: 2cb749301f2c
Create Date: 2026-09-21 14:02:19.482039
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '80e25247c90a'
down_revision: str | None = '2cb749301f2c'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoi_thoai',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('conversation_id', sa.String(length=256), nullable=False),
    sa.Column('tieu_de', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tao_luc', sa.Float(), nullable=False),
    sa.Column('cap_nhat_luc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoi_thoai')
    # ### end Alembic commands ###
